### ISSUE TITLE
Incorrect winnow information in docs

### ISSUE THREAD

**Issue by epage** [Easyoakland/yap_streaming#1] opened 2023-10-28 01:02 UTC
> nom and winnow are very similar and share a few problems:
>
> - No obvious way to signal the end of a stream to a parser.

You can use [StreamIsPartial::complete](https://docs.rs/winnow/latest/winnow/stream/trait.StreamIsPartial.html#tymethod.complete) for this.

**Comment by epage** [comment] 2023-10-28 01:13
Also not entirely sure this is accurate

> The user of the library has to implement a streaming parser noticeably differently from a non-streaming parser.

The differences between our [com, you plete](https://github.com/winnow-rs/winnow/blob/main/examples/json/parser.rs) and [partial](https://github.com/winnow-rs/winnow/blob/main/examples/json/parser_partial.rs) json parsers is minimal.

I also feel that, while accurate, the following can be misleading

> Running out of input requires re-parsing from scratch and redoing work.

Generally, a parser for partial input will be operator on a frame at a time.  For fixed size frames, you don't even need to treat it as partial input.  For variable sizes frames (e.g. json lines), you do need to reparse but only for the current frame.  This can also be bypassed by seeking ahead to the frame delimiter and then parsing that.

**Comment by Easyoakland** [comment] 2023-10-28 06:11
First, I assume you have no problem with those descriptors applying to `nom`?

---

I'm not sure what "com, you plete" refers to. I'll assume that's just `complete`.

While [StreamIsPartial::complete](https://docs.rs/winnow/latest/winnow/stream/trait.StreamIsPartial.html#tymethod.complete) is available, you'd have to write the parser to explicitly check this which would require changing the parser to handle partial input. It does exist so I'll remove the point for `winnow`.

---

I'll admit that I don't think the differences for `winnow` between the streaming and non-streaming versions were very different, but I was trying to make the point that you don't need to change the parser _at all_ for `yap_streaming`. I could change the statement to
>    The user of the library has to implement a streaming parser differently from a non-streaming parser.

if your problem is just the severity of the statement.

---

Would this be sufficient?
>    Parsing occurs on chunks. Parsing dynamically sized chunks can require re-parsing the chunk from scratch and redoing work.

---
I'm not sure what this means 
> This can also be bypassed by seeking ahead to the frame delimiter and then parsing that.

Is this saying do something like `iter.take_while(|x| !is_frame_delim(x))` to avoid using a partial parser?

**Comment by epage** [comment] 2023-10-29 02:39
> First, I assume you have no problem with those descriptors applying to nom?

The frame processing comment applies to nom as well.  The rest is accurate.

> I'll admit that I don't think the differences for winnow between the streaming and non-streaming versions were very different, but I was trying to make the point that you don't need to change the parser at all for yap_streaming. I could change the statement to

One big change `winnow` made was that the `streaming` and `complete` parser combinators were merged, auto-detecting what to do based on the Input.

The top-level needs special handling for retrying just like yap_streaming, though with more ceremony.

> > This can also be bypassed by seeking ahead to the frame delimiter and then parsing that.
>
> Is this saying do something like iter.take_while(|x| !is_frame_delim(x)) to avoid using a partial parser?

You use the partial parsing to take everything until the delimiter and then you do complete parsing on that acquired slice.  This does require a frame to fit within memory but all that is already a limitation with everything else winnow does.

**Comment by epage** [comment] 2023-10-29 02:41
btw how would you handle IO errors with yap_streaming?  The primary example looks to just treat it as EOF and not report it back up (instead at best an incomplete parse would fail, returning that message, at worst you get ailence)

**Comment by Easyoakland** [comment] 2023-10-29 05:41
> One big change winnow made was that the streaming and complete parser combinators were merged, auto-detecting what to do based on the Input.
> 
> The top-level needs special handling for retrying just like yap_streaming, though with more ceremony.

Looking at your complete/partial example again and I believe your point is valid. I'll remove the comment for `winnow`.

---

> You use the partial parsing to take everything until the delimiter and then you do complete parsing on that acquired slice. This does require a frame to fit within memory but all that is already a limitation with everything else winnow does.

How does the partial parser know how much to take to know where the delimiter is? It seems like the problem is the same. How do you "seeking ahead to the frame delimiter"?

---

> btw how would you handle IO errors with yap_streaming? The primary example looks to just treat it as EOF and not report it back up (instead at best an incomplete parse would fail, returning that message, at worst you get ailence)

I think you're right in that the example should panic instead of just pretending an EOF. I'll fix that. In general you should be able to handle errors by implementing a custom iterator/adapter that does whatever behavior you want on fail (retry the file, send an error to a channel, and panic, etc.).

> but also blocking in the parser could end up with serious ramifications for an application.

For blocking, you can spawn a thread and communicate the parse result with a channel. I don't see why this would imply "serious ramifications" unless you're indicating that it's not sufficiently clear that the parser will block while waiting for input.

**Comment by epage** [comment] 2023-10-30 14:10
> How does the partial parser know how much to take to know where the delimiter is? It seems like the problem is the same. How do you "seeking ahead to the frame delimiter"?

Its the same as parsing without looking ahead to the frame delimiter, it just saves you in doing throwaway parse work.

> I think you're right in that the example should panic instead of just pretending an EOF. I'll fix that. In general you should be able to handle errors by implementing a custom iterator/adapter that does whatever behavior you want on fail (retry the file, send an error to a channel, and panic, etc.).

imo error handling is a core part of the problem space but its likely for people to mimic your docs if you gloss over it.

If I implemented support for this within clap, what I was considering was to have the error saved into the stream and the caller can check the status of the error at the end (since they still have the stream in the end).

> For blocking, you can spawn a thread and communicate the parse result with a channel. I don't see why this would imply "serious ramifications" unless you're indicating that it's not sufficiently clear that the parser will block while waiting for input.

That is then incompatible with async/await.

**Comment by Easyoakland** [comment] 2023-10-30 17:26
> imo error handling is a core part of the problem space but its likely for people to mimic your docs if you gloss over it.

How should the example handle the error then?

> If I implemented support for this within clap, what I was considering was to have the error saved into the stream and the caller can check the status of the error at the end (since they still have the stream in the end).

Yes, it is true that you could also parse your stream as a `Result<Item, IO or parse error>` and report an io error for the span on which the io errors occur the same as you would a parse error.

> That is then incompatible with async/await.

Isn't that what `spawn_blocking` or https://github.com/smol-rs/blocking is for? You could re-implement the whole thing with [Stream](https://docs.rs/futures-core/latest/futures_core/stream/trait.Stream.html) but I don't have a present interest or need for doing that.

**Comment by epage** [comment] 2023-10-30 19:40
Oops, said clap instead of winnow :)

The example should show how to propagate the error up.

Also, the example incorrectly turns a stream of bytes into `char`s which can corrupt the data, whether its bytes or utf8.  If you need a state machine to turn it into utf8, I'd recommend `utf8parse`.

> Isn't that what spawn_blocking or https://github.com/smol-rs/blocking is for? You could re-implement the whole thing with [Stream](https://docs.rs/futures-core/latest/futures_core/stream/trait.Stream.html) but I don't have a present interest or need for doing that.

I thought `spawn_block` is for when your calculations will be expensive.  This is mixing IO and calculations and shoving it off onto a thread, rather than making the IO use async, which is part of the point of async.

**Comment by Easyoakland** [comment] 2023-10-31 06:00
> The example should show how to propagate the error up.

> Also, the example incorrectly turns a stream of bytes into chars which can corrupt the data, whether its bytes or utf8. If you need a state machine to turn it into utf8, I'd recommend utf8parse.

You mean like this?

```rust

    // Instead of parsing an in-memory buffer we can use `yap_streaming` to parse a stream.
    // While we could just [`std::io::Read::read_to_end()`] here, what if the file was too large to fit in memory?
    // What if we were parsing from a network socket?

    struct Utf8Reader(Option<Result<char, std::io::Error>>);
    impl utf8parse::Receiver for Utf8Reader {
        fn codepoint(&mut self, c: char) {
            self.0 = Some(Ok(c))
        }

        fn invalid_sequence(&mut self) {
            self.0 = Some(Err(std::io::ErrorKind::InvalidData.into()))
        }
    }

    let mut parser = utf8parse::Parser::new();
    let mut receiver = Utf8Reader(None);

    // Save io_error if one occurs.
    let mut io_err = None;
    let file_chars = BufReader::new(File::open("examples/opOrDigit.txt").unwrap())
        .bytes()
        .flat_map(|x| {
            if let Ok(b) = x {
                parser.advance(&mut receiver, b)
            };
            receiver.0.take()
        })
        .map_while(|x| {
            match x {
                Ok(x) => Some(x),
                Err(e) => {
                    io_err = Some(e);
                    // Don't parse any further if io error.
                    // Alternatively could panic, retry the byte, or include as an error variant and parse Result<char, ParseError> instead.
                    None
                }
            }
        });
    // Convert to something implementing `Tokens`
    let mut tokens = StreamTokens::into_tokens(file_chars);
    // Parse
    assert_eq!(eval(&mut tokens), 140);
    // Check that parse encountered no io errors.
    assert!(io_err.is_none());
```

that's rather long for an example that's meant to focus on what's unique about `yap_streaming`. I can include an example that does this, but I don't think it would be a good introductory example to put in the README.

> I thought spawn_block is for when your calculations will be expensive. This is mixing IO and calculations and shoving it off onto a thread, rather than making the IO use async, which is part of the point of async.

1. First sentence in [blocking](https://github.com/smol-rs/blocking): "A thread pool for isolating blocking I/O in async programs." So I don't think your statement is fully true?
2. The need to benchmark parsers that use in-memory buffers implies significant cpu time.
3. As stated [here](https://ryhl.io/blog/async-what-is-blocking/) "a good rule of thumb is no more than 10 to 100 microseconds between each .await" which is much less than the benchmarks at [parse-rosetta-rs](https://github.com/rosetta-rs/parse-rosetta-rs). Following that guideline would lead to using `spawn_blocking` anyway.

**Comment by Easyoakland** [comment] 2023-11-12 10:33
I think the initial reason this issue was opened "incorrect winnow information in docs" is rectified in #2, so I'll close it.

I would be interested if my understanding of `spawn_blocking` and related is incorrect, but if you decide to answer you should be able to do so in the closed issue or in a new one.

Thanks for the discussion @epage! 😄

**Closed as completed by Easyoakland** 2023-11-12 10:33 UTC
